### PR TITLE
Bugfix/wrong ipv6 addresses

### PR DESCRIPTION
**Pull request by cscheuermann-81**

### CODE REVIEW

**Comment by cscheuermann-81** [comment]
related to issue #48

**Comment by dadepo** [comment]
Thanks for this. I am neck deep with a project at the Uni at the moment, so it might take until next week before before I get the chance to review and merge.

**Comment by dadepo** [comment]
Thanks for this..I will push a release soon.

**Comment by dadepo** [comment]
v1.2.3 released

**Pull request merged**
